### ISSUE TITLE
Kanban board

### ISSUE THREAD

**Issue by Zilola-Nazarova** [Zilola-Nazarova/space-travelers-hub#25]
Our Kanban board link:
https://github.com/Zilola-Nazarova/space-travelers-hub/projects/1

There are 2 people in our team: @Lawmsangi and @Zilola-Nazarova

**Comment by levy002** [comment]
## Hello @Zilola-Nazarova  & @Lawmsangi   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] Kindly assign the group task cards to all group members. We should see a circle with both member's avatars on the group task card. See the example below:

  
   ![image](https://github.com/Zilola-Nazarova/space-travelers-hub/assets/87197412/4ea1d044-99eb-44ae-bed1-e88723bf155f)



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by topeogunleye** [comment]
Hi @Zilola-Nazarova, @Lawmsangi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![dwayne-the-rock](https://user-images.githubusercontent.com/52934128/180645370-67438f1f-e27d-4f8b-88d6-1e3474394f0a.gif)

## (Highlights) Good Points: 💪 
* Assigned the group task cards to all group members

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- Nothing to mention.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
